version: '3.4'

services:
  blogwebsite:
    image: blogwebsite
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
